name: Deploy API

on:
  push:
    branches: [master]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lightgbm  


      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}   # Add root to PYTHONPATH
        run: |
          pytest tests/

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/maze-gesture-api:latest

      # - name: SSH deploy to server
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ubuntu
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/maze-gesture-api:latest
      #       docker stop maze_api || true && docker rm maze_api || true
      #       docker run -d --name maze_api -p 80:8000 \
      #         ${{ secrets.DOCKERHUB_USERNAME }}/maze-gesture-api:latest
